# HOW TO USE THIS docker-compose.yaml
# https://docs.docker.com/compose/compose-file/

# docker-compose up -d
# docker exec <redix-client-1 id> -it bash
# docker exec <redix-client-2 id> -it bash

version: '3'

services:
  postgres-bdp:
    image: postgres
    ports:
      - 5433:5433
  redis-server:
    image: redis
    ports: 
      - 6379:6379
  redis-client-1:
    image: redis
    network_mode: bridge
    # command: redis-cli -h 172.17.0.2 <--- if I put this in, then the container won't stay running
    depends_on:
      - redis-server
  redis-client-2:
    image: redis
    network_mode: bridge
    # command: redis-cli -h 172.17.0.2 <--- if I put this in, then the container won't stay running
    depends_on:
      - redis-server