# HOW TO USE THIS docker-compose.yaml
# docker-compose up -d
# docker-compose run redis-client-1 redis-cli -h 172.17.0.2
# docker-compose run redis-client-2 redis-cli -h 172.17.0.2

version: '3'

services:
  postgres-bdp:
    image: postgres
    ports:
      - 5433:5433
  redis-server:
    image: redis
    ports: 
      - 6379:6379
  redis-client-1:
    image: redis
    network_mode: bridge
  redis-client-2:
    image: redis
    network_mode: bridge