# HOW TO USE THIS docker-compose.yaml
# https://docs.docker.com/compose/compose-file/

# `docker-compose up -d`
# `docker exec <redix-client-1 id> -it bash`
# `docker exec <redix-client-2 id> -it bash`
# and then start redis-cli in each one, manually

version: '3'

# TODO need to add `link` `--link` commands to get redis-cli clients connecting to redis-server properly

services:
  postgres-bdp:
    image: postgres
    ports:
      - 5433:5433
    # container_name: '' <--- optional. "Because Docker container names must be unique, you cannot scale a service beyond 1 container if you have specified a custom name. ""
  redis-server:
    image: redis
    ports: 
      - 6379:6379
  redis-client-1:
    image: redis
    network_mode: bridge
    # command: redis-cli -h 172.17.0.2 <--- if I put this in, then the container won't stay running
    # command: redis-cli -h redis-server <---- can also try putting container-name
    depends_on:
      - redis-server
    # links:                 <-------- might fix it, according to example solution...
      # - redis-server
  redis-client-2:
    image: redis
    network_mode: bridge
    # command: redis-cli -h 172.17.0.2 <--- if I put this in, then the container won't stay running
    depends_on:
      - redis-server



# Interesting...
# For docker run, --link is also deprecated and should be replaced by a custom network. 
# https://stackoverflow.com/questions/35832095/difference-between-links-and-depends-on-in-docker-compose-yml



# docker exec vs docker attach
# https://stackoverflow.com/questions/30960686/difference-between-docker-attach-and-docker-exec
# "exec is for running new command"