version: '3'

services:
  redis-server:
    image: redis
    ports: 
      - 8081:6379
      # 6379: 6379
  python-redis-1:
    build: .
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis-server
    command: "python redis-client.py query1 --file file-input1.csv"
