# https://docs.docker.com/compose/compose-file/

# `docker-compose up -d`
# `docker exec <redix-client-1 id> -it bash`
# `docker exec <redix-client-2 id> -it bash`
# and then start redis-cli in each one, manually

version: '3'

# TODO need to add `link` `--link` commands to get redis-cli clients connecting to redis-server properly

services:
  redis-server:
    image: redis
    ports: 
      - 6379:6379
  python-redis-1:
    build: .
    ports:
      - "8080:6379"
  # redis-client-1:
  #   image: redis
  #   network_mode: bridge
  #   # command: redis-cli -h 172.17.0.2 <--- if I put this in, then the container won't stay running
  #   depends_on:
  #     - redis-server
