version: '3.5'
networks:
  kafka-demo:
    name: kafka-demo-net
    driver: bridge

services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
    networks:
      - kafka-demo
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    environment:
      # KAFKA_BROKER_ID: 1
      # (Hack for Mac)use this if you want to have docker host node to be used as broadcast ip
      HOSTNAME_COMMAND: "/sbin/ip route|awk '/src/ { print $$NF }'"
      # Use below for Linux
      # HOSTNAME_COMMAND: "ip route get 1.2.3.4 | awk '{print $$7}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "varnish_raw_logs:10:1"
    depends_on:
      - zookeeper
    ports:
      - 9092
    networks:
      - kafka-demo

  python-example:
    # image: python:alpine3.10
    image: python:2.7.16-alpine3.10
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - "./python:/python"
    command: 'sleep 5000'
    networks:
      - kafka-demo  